// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1atSsbVu-__88SNk_PPkaQfBpqFnO_0',
    appId: '1:377693109348:web:c1b79721e71e2c85d6b371',
    messagingSenderId: '377693109348',
    projectId: 'flutterfirestoreproject-8bd16',
    authDomain: 'flutterfirestoreproject-8bd16.firebaseapp.com',
    storageBucket: 'flutterfirestoreproject-8bd16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwOWwNSzzDKlvi6Jm7MNj6oSab3xfQ-8',
    appId: '1:377693109348:android:e0dcd7e9d5b9f895d6b371',
    messagingSenderId: '377693109348',
    projectId: 'flutterfirestoreproject-8bd16',
    storageBucket: 'flutterfirestoreproject-8bd16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZWKNumaPGMsMkWY4kCJBdeeguyHx4igM',
    appId: '1:377693109348:ios:c5f8ee57199a06bed6b371',
    messagingSenderId: '377693109348',
    projectId: 'flutterfirestoreproject-8bd16',
    storageBucket: 'flutterfirestoreproject-8bd16.appspot.com',
    iosClientId: '377693109348-tj25l5m5fs5mvnpd4dj4vgke9psanqqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFstoreProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZWKNumaPGMsMkWY4kCJBdeeguyHx4igM',
    appId: '1:377693109348:ios:c5f8ee57199a06bed6b371',
    messagingSenderId: '377693109348',
    projectId: 'flutterfirestoreproject-8bd16',
    storageBucket: 'flutterfirestoreproject-8bd16.appspot.com',
    iosClientId: '377693109348-tj25l5m5fs5mvnpd4dj4vgke9psanqqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFstoreProject',
  );
}
